# Global settings applied to the whole site.
[build]
  base    = "/"
  publish = "app/"
  command = "npm install && npm run setup"

# Read https://www.netlify.com/docs/continuous-deployment/#deploy-contexts
# to understand how context below works.

# Master branch
[context.production.environment]
  APIHOST = "https://api.targetvalidation.org/api/"

# Deploy Preview context: All Deploy Previews (ie.PRs)
# will inherit these settings.
[context.deploy-preview.environment]
  APIHOST = "https://api.targetvalidation.org/api/"

# Branch Deploy context: All deploys that are not in
# an active Deploy Preview will inherit these settings.
[context.branch-deploy.environment]
  APIHOST = "https://api.targetvalidation.org/api/"

# CAREFUL!!! When you point a particular branch to a specific API below,
# the change will not continue working once the branch is merged into master.
[context.feature.environment]
  APIHOST = "https://api.targetvalidation.org/api/"

[context.master.environment]
  APIHOST = "https://api.targetvalidation.org/api/"
